apiVersion: v1
data:
  application.yml: |
    server:
      port: 8090

    spring:
      datasource:
        url: jdbc:mysql://172.20.217.93:3306/test_memsql
        password: 'test_user'
        username: test_user
      jpa:
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
      zipkin:
        sender:
          type: kafka
      sleuth:
        sammpler:
          rate: 1000
      kafka:
        bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:http://172.20.86.66:9092}
        producer:
          retries: 3
          properties:
            retry.backoff.ms: 10000
            max.block.ms: 6000
            delivery.timeout.ms: 40000
            reconnect.backoff.ms: 50000
            reconnect.backoff.max.ms: 100000
        admin:
          properties:
            bootstrap.servers: 192.168.99.100:9092

    logger:
      kafka:
        topic: customercreationlogs
        bootstrap-servers: http://172.20.86.66:9092
        retries: 2
        delivery.timeout.ms: 40000
        reconnect.backoff.ms: 50000
        reconnect.backoff.max.ms: 100000
        retry.backoff.ms: 10000
        max.block.ms: 6000
kind: ConfigMap
metadata:
  name: product-catalog-api-v1
  namespace: plm-dev

